### ISSUE TITLE
Problème commit

### ISSUE THREAD

**Issue by jschuwey** [Bassim789/textable-pattern-web#6]
Salut les gars, je crois qu'il y a un petit problème avec mes commit lol j'espère que j'ai pas fait n'importe quoi.... En fait j'utilise Github Desktop et je n'arrivais pas à commit donc je sais pas trop ce que j'ai fait. Sinon je voulais juste essayer d'ajouter Bing au widget à la base et ça semble marcher mais dites-moi si y'a un souci.

**Comment by Bassim789** [comment]
Salut, c'est tout bon. J'ai fais une ou deux petite modif et Bing marche bien. ++
